In [2]:
import sys
!{sys.executable} -m pip --default-timeout=100 install numpy

In [3]:
!{sys.executable} -m pip --default-timeout=100 install scikit-learn

In [4]:
!{sys.executable} -m pip --default-timeout=100 install pandas

In [5]:
import numpy as np

In [6]:
import pandas as pd

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
df = pd.read_csv('/Users/apple/Desktop/666/Sheet 3-y.csv')

In [115]:
dp = pd.read_csv('/Users/apple/Desktop/newww.csv')

In [121]:
print(df['year'])

0     2001
1     2002
2     2003
3     2004
4     2005
5     2006
6     2007
7     2008
8     2009
9     2010
10    2011
11    2012
12    2013
13    2014
14    2015
15    2016
16    2017
17    2018
18    2019
19    2020
Name: year, dtype: int64


In [9]:




#x = np.array([2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020]).reshape((-1, 1))
#y = np.array([2682536,2754258,2822384,2873351,2933746,2997856,3049224,3120048,3178777,3249418,3310682,3373564,3446548,3519491,3581815,3666505,3750484,3838133,3907572,3963818,3970844])

x = np.array(df[['year']]).reshape(-1, 1)
y = np.array(df['vehicle'])

model = LinearRegression()

model.fit(x, y)

##r_sq = model.score(x, y)
#print('coefficient of determination:', r_sq)

print('intercept:', model.intercept_)

print('slope:', model.coef_)

intercept: -207322990.17067674
slope: [105902.7593985]


In [11]:
model.predict(np.array([2030]).reshape((-1, 1)))

array([7659611.40827066])

In [114]:
model.predict(dp[['population','75%']])

/opt/anaconda3/envs/fit5197/lib/python3.8/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- 75%
Feature names seen at fit time, yet now missing:
- passenger_vehciles

  warnings.warn(message, FutureWarning)


array([22194.43802465, 22550.01520134, 22809.76060264, 22907.70321008,
       23055.24612782, 23323.4669795 , 23396.5586383 , 23676.03119514,
       23801.2991767 , 24067.16965345, 24264.25570004, 24409.36000506,
       24623.67209452, 24910.00446821, 24985.1989124 , 25213.2957491 ,
       25415.52915745, 25762.21573606, 26078.2625059 , 26630.06953314])

In [40]:
model.predict(np.array([2040]).reshape((-1, 1)))

array([5336913.25541125])

In [70]:
model.predict(np.array(dp['passenger_vehicles']).reshape((-1, 1))).to_csv('/Users/apple/Desktop/population/output.csv')  

AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'